# Generated by Django 4.2.1 on 2023-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="sector",
            field=models.CharField(default="Government", max_length=40),
            preserve_default=False,
        ),
    ]
