# Generated by Django 4.2.1 on 2023-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_appuser_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="role",
            field=models.CharField(default="Law Enforcement", max_length=255),
            preserve_default=False,
        ),
    ]
