# Generated by Django 4.2.1 on 2023-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_appuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="countryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=100)),
                ("users", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Stats By Country",},
        ),
    ]
