# Generated by Django 4.2.1 on 2023-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_countrystats"),
    ]

    operations = [
        migrations.RemoveField(model_name="countrystats", name="country_code",),
        migrations.RemoveField(model_name="countrystats", name="users",),
        migrations.AddField(
            model_name="appuser",
            name="country",
            field=models.CharField(default="Kenya", max_length=100),
        ),
    ]
