# Generated by Django 4.2.1 on 2023-08-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_countrystats_country_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrystats", options={"verbose_name_plural": "Country Statistics"},
        ),
        migrations.AddField(
            model_name="countrystats",
            name="users",
            field=models.IntegerField(default=0),
        ),
    ]
