# Generated by Django 4.2.1 on 2024-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_countrystats_options_countrystats_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='Kenya', max_length=100, null=True),
        ),
    ]
