# Generated by Django 4.2.1 on 2024-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
