# Generated by Django 5.1 on 2024-11-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_countrycount_institutioncount_rolecount_sectorcount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyuserregistration',
            options={'verbose_name_plural': 'Registration per Month'},
        ),
    ]
